---------BANCO 
CREATE DATABASE ConcessionariaDW

----------- TABELA DIM_CLIENTE
 CREATE TABLE DIM_CLIENTE(
 CODCLIENTE INT IDENTITY PRIMARY KEY,
 NOMECLIENTE VARCHAR(100)NOT NULL,
 );


--------- TABELA DIM_LOJA
 CREATE TABLE DIM_LOJA(
 CODLOJA INT IDENTITY PRIMARY KEY,
 ESTADO VARCHAR(100)NOT NULL,
 CIDADE VARCHAR(100)NOT NULL
 );

--------- TABELA DIM_TEMPO

 CREATE TABLE DIM_TEMPO(
 CODDATA INT IDENTITY PRIMARY KEY,
 DATA DATE NOT NULL,
 ANO INT NOT NULL,
 MES VARCHAR(100)NOT NULL
 );


--------- TABELA DIM_VEICULO
 CREATE TABLE DIM_VEICULO(
 CODVEICULO INT IDENTITY PRIMARY KEY,
 COR VARCHAR(100)NOT NULL,
 FABRICANTE VARCHAR(100)NOT NULL,
  MODELO VARCHAR(100)NOT NULL
 );
 
 --------- TABELA FATO_VENDA
 CREATE TABLE FATO_VENDA(
 CODVENDA INT IDENTITY PRIMARY KEY,
 COR VARCHAR(100)NOT NULL,
 VALORVENDA FLOAT NOT NULL,

 );
 


